### ISSUE TITLE
изменённая система для новеньких

### ISSUE THREAD

**Issue by EnderDissa** [lapitan/Joupen#6]
joupen prolongnovichek <nick> 10d | joupen prolong <nick> и проверка, новичок ли он

считать дни с момента, когда он первый раз зашёл. помечать, что он новичок и дни получены бесплатно

**Comment by Stunnerer** [comment]
предполагаю сделать что-то типа 
newplayers.json
```json
{
  "username": "<nick>", 
  "time": "10d8h"
}
```
onplayerjoin() -> checkIfNew() -> prolong()

**Comment by lapitan** [comment]
но тебе все еще придется их добавлять в ручную, так ведь? С помощью команд или чего еще

**Comment by Stunnerer** [comment]
> в ручную

не, вместе с https://github.com/lapitan/Joupen/issues/5 можно будет сделать красиво

**Comment by lapitan** [comment]
если придумаете как поднять спрингбут из-под java plugin'а- сделаю.
Без спрингбута мне впадлу туда лезть

**Comment by lapitan** [comment]
но даже так, придется подтверждать формы и так далее. Полностью автоматизировать- анриал. Будет просто "нажмите кнопочку да, если все ок"

**Comment by EnderDissa** [comment]
это вообще не о сервере тикет. тут вопрос, что новенький игрок должен в системе чуть иначе отображаться, т.к. он не покупает проходку, а бесплатно её получает.

**Comment by EnderDissa** [comment]
условно, сейчас на спартакиаде 400+ чел выиграло разное количество дней, можно было бы им сразу всем прописать, а при первом входе эти дни начислились бы
